# Generated by Django 3.0.7 on 2021-06-26 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tdados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dados',
            name='estado',
        ),
    ]
